### ISSUE TITLE
Possible to add inputs of type array or record?

### ISSUE THREAD

**Issue by allanbolipata** [NLeSC/scriptcwl#110]
Trying to see if there is a way to add_input of type `array` or `record`, or some combination containing one or more of these with `scriptcwl`. For example, how would someone add an input like the following to their workflow?
```
  my_array_of_array_of_strings:
    type:
      type: array
      items:
        type: array
        items: string
```
I couldn't find anything in the examples.
