### ISSUE TITLE
Does not understand tools written with shortcuts 

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/scriptcwl#12]
An inputs written as:
```
inputs:
  message:
    type: string
    inputBinding:
      position: 1
```

Is not understood and gets loaded as a step without inputs
