### ISSUE TITLE
Allow step to be scattered

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/scriptcwl#17]
See example scatter workflow https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/scatter-wf2.cwl

Example implementation if step was called `echo` to scatter it use:
```python
echo_out = workflow.echo(echo_in1=inp1, echo_in2=inp2, scatter=[echo_in1, echo_in2], scatter_method='nested_crossproduct')
```

This would generated the following cwl file
```yaml
requirements:
- class: ScatterFeatureRequirement
....
steps:
  echo:
    in:
      echo_in1: inp1
      echo_in2: inp2
    out: [echo_out]
    scatter: [echo_in1, echo_in2]
    scatterMethod: nested_crossproduct
```
