### ISSUE TITLE
Recursive inline saving

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/scriptcwl#84]
The result of saving a workflow with a subworkflow with inline steps has ugly ids and outputSources:

```
  align-texts-wf:
    run:
      cwlVersion: v1.0
      class: Workflow
      requirements:
      - class: ScatterFeatureRequirement
      inputs:
      - type:
        - 'null'
        - string
        id: _:align-texts-wf#align_c
      - type:
        - 'null'
        - string
        id: _:align-texts-wf#align_m
      - type:
          type: array
          items: File
        id: _:align-texts-wf#gs
      - type:
          type: array
          items: File
        id: _:align-texts-wf#ocr
      outputs:
      - type:
          items: File
          type: array
        outputSource: file:///home/jvdzwaan/code/ocr/cwl/align-texts-wf.cwl#char-align/out_file
        id: _:align-texts-wf#alignments
      - type: File
        outputSource: file:///home/jvdzwaan/code/ocr/cwl/align-texts-wf.cwl#merge-json-1/merged
        id: _:align-texts-wf#changes
      - type: File
        outputSource: file:///home/jvdzwaan/code/ocr/cwl/align-texts-wf.cwl#merge-json/merged
        id: _:align-texts-wf#metadata
```

Also the problem of duplicate ids arises if a subworkflow is added multiple times (related to #82).
