### ISSUE TITLE
step with multiple outputs

### ISSUE THREAD

**Issue by KerstenBreuer** [NLeSC/scriptcwl#95]
In the documentation, I couldn't find how to deal with commandLineTools that produce more than a single output. Maybe I missed it, but how would you realize a workflow like this (stepA has two outputs that are used by different subsequent steps):

```
cwlVersion: v1.0
class: Workflow

inputs:
    wf_input:
        type: File

steps:
    stepA:
        run: ./toolA.cwl
        in:
            in_file:
                source: wf_input
        out:
            - out_file_X
            - out_file_Y
    stepB:
        run: ./toolB.cwl
        in:
            in_file:
                source: stepA/out_file_X
        out:
            - out_file_X2
    stepC:
        run: ./toolC.cwl
        in:
            in_file:
                source: stepA/out_file_Y
        out:
            - out_file_Y2

outputs:
    out_file_X2:
        type: File
        outputSource: stepB/out_file_X2
    out_file_Y2:
        type: File
        outputSource: stepC/out_file_Y2
```
